# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build MoltenVK
        shell: bash
        run: |
          brew install cmake
          brew install python3
          brew install ninja
          git clone https://github.com/KhronosGroup/MoltenVK.git
          cd MoltenVK
          echo 9acb9ec31f5a8ef80ea6b994bb77be787b08d3d1 > ExternalRevisions/SPIRV-Cross_repo_revision
          ./fetchDependencies --macos
          xcodebuild build -quiet -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (macOS only)" -configuration "Release"
          tar zcvf ../MoltenVK-Package.tar.gz Package/Latest
          ls
          cd ..
          ls

      - name: Upload Package
        uses: actions/upload-artifact@v1
        with:
          name: "MoltenVK-Package"
          path: "MoltenVK-Package.tar.gz"
